/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.14.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.ob.domain.yapilymodels;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * Information about a user of an application.
 */
@ApiModel(description = "Information about a user of an application.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-16T14:42:32.575816279Z[Europe/London]")
public class ApplicationUser {
  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  private UUID uuid;

  public static final String SERIALIZED_NAME_APPLICATION_UUID = "applicationUuid";
  @SerializedName(SERIALIZED_NAME_APPLICATION_UUID)
  private UUID applicationUuid;

  public static final String SERIALIZED_NAME_APPLICATION_USER_ID = "applicationUserId";
  @SerializedName(SERIALIZED_NAME_APPLICATION_USER_ID)
  private String applicationUserId;

  public static final String SERIALIZED_NAME_REFERENCE_ID = "referenceId";
  @SerializedName(SERIALIZED_NAME_REFERENCE_ID)
  private String referenceId;

  public static final String SERIALIZED_NAME_INSTITUTION_CONSENTS = "institutionConsents";
  @SerializedName(SERIALIZED_NAME_INSTITUTION_CONSENTS)
  private List<InstitutionConsent> institutionConsents = null;

  public ApplicationUser() { 
  }

  public ApplicationUser uuid(UUID uuid) {
    
    this.uuid = uuid;
    return this;
  }

   /**
   * A unique identifier for the &#39;User&#39; assigned by Yapily.
   * @return uuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A unique identifier for the 'User' assigned by Yapily.")

  public UUID getUuid() {
    return uuid;
  }


  public void setUuid(UUID uuid) {
    this.uuid = uuid;
  }


  public ApplicationUser applicationUuid(UUID applicationUuid) {
    
    this.applicationUuid = applicationUuid;
    return this;
  }

   /**
   * Unique identifier of the application the user is associated with.
   * @return applicationUuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Unique identifier of the application the user is associated with.")

  public UUID getApplicationUuid() {
    return applicationUuid;
  }


  public void setApplicationUuid(UUID applicationUuid) {
    this.applicationUuid = applicationUuid;
  }


  public ApplicationUser applicationUserId(String applicationUserId) {
    
    this.applicationUserId = applicationUserId;
    return this;
  }

   /**
   * __Conditional__. The user-friendly reference to the &#x60;User&#x60;.
   * @return applicationUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "__Conditional__. The user-friendly reference to the `User`.")

  public String getApplicationUserId() {
    return applicationUserId;
  }


  public void setApplicationUserId(String applicationUserId) {
    this.applicationUserId = applicationUserId;
  }


  public ApplicationUser referenceId(String referenceId) {
    
    this.referenceId = referenceId;
    return this;
  }

   /**
   * Get referenceId
   * @return referenceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getReferenceId() {
    return referenceId;
  }


  public void setReferenceId(String referenceId) {
    this.referenceId = referenceId;
  }


  public ApplicationUser institutionConsents(List<InstitutionConsent> institutionConsents) {
    
    this.institutionConsents = institutionConsents;
    return this;
  }

  public ApplicationUser addInstitutionConsentsItem(InstitutionConsent institutionConsentsItem) {
    if (this.institutionConsents == null) {
      this.institutionConsents = new ArrayList<InstitutionConsent>();
    }
    this.institutionConsents.add(institutionConsentsItem);
    return this;
  }

   /**
   * Get institutionConsents
   * @return institutionConsents
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<InstitutionConsent> getInstitutionConsents() {
    return institutionConsents;
  }


  public void setInstitutionConsents(List<InstitutionConsent> institutionConsents) {
    this.institutionConsents = institutionConsents;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplicationUser applicationUser = (ApplicationUser) o;
    return Objects.equals(this.uuid, applicationUser.uuid) &&
        Objects.equals(this.applicationUuid, applicationUser.applicationUuid) &&
        Objects.equals(this.applicationUserId, applicationUser.applicationUserId) &&
        Objects.equals(this.referenceId, applicationUser.referenceId) &&
        Objects.equals(this.institutionConsents, applicationUser.institutionConsents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, applicationUuid, applicationUserId, referenceId, institutionConsents);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplicationUser {\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    applicationUuid: ").append(toIndentedString(applicationUuid)).append("\n");
    sb.append("    applicationUserId: ").append(toIndentedString(applicationUserId)).append("\n");
    sb.append("    referenceId: ").append(toIndentedString(referenceId)).append("\n");
    sb.append("    institutionConsents: ").append(toIndentedString(institutionConsents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

