/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.14.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.ob.domain.yapilymodels;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

/**
 * Enrichment
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-16T14:42:32.575816279Z[Europe/London]")
public class Enrichment {
  public static final String SERIALIZED_NAME_CATEGORISATION = "categorisation";
  @SerializedName(SERIALIZED_NAME_CATEGORISATION)
  private Categorisation categorisation;

  public static final String SERIALIZED_NAME_TRANSACTION_HASH = "transactionHash";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_HASH)
  private TransactionHash transactionHash;

  public static final String SERIALIZED_NAME_CLEANSED_DESCRIPTION = "cleansedDescription";
  @SerializedName(SERIALIZED_NAME_CLEANSED_DESCRIPTION)
  private String cleansedDescription;

  public static final String SERIALIZED_NAME_MERCHANT = "merchant";
  @SerializedName(SERIALIZED_NAME_MERCHANT)
  private EnrichmentMerchant merchant;

  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  private String location;

  public static final String SERIALIZED_NAME_PAYMENT_PROCESSOR = "paymentProcessor";
  @SerializedName(SERIALIZED_NAME_PAYMENT_PROCESSOR)
  private String paymentProcessor;

  public static final String SERIALIZED_NAME_CORRECTED_DATE = "correctedDate";
  @SerializedName(SERIALIZED_NAME_CORRECTED_DATE)
  private OffsetDateTime correctedDate;

  public Enrichment() { 
  }

  public Enrichment categorisation(Categorisation categorisation) {
    
    this.categorisation = categorisation;
    return this;
  }

   /**
   * Get categorisation
   * @return categorisation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Categorisation getCategorisation() {
    return categorisation;
  }


  public void setCategorisation(Categorisation categorisation) {
    this.categorisation = categorisation;
  }


  public Enrichment transactionHash(TransactionHash transactionHash) {
    
    this.transactionHash = transactionHash;
    return this;
  }

   /**
   * Get transactionHash
   * @return transactionHash
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TransactionHash getTransactionHash() {
    return transactionHash;
  }


  public void setTransactionHash(TransactionHash transactionHash) {
    this.transactionHash = transactionHash;
  }


  public Enrichment cleansedDescription(String cleansedDescription) {
    
    this.cleansedDescription = cleansedDescription;
    return this;
  }

   /**
   * Get cleansedDescription
   * @return cleansedDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCleansedDescription() {
    return cleansedDescription;
  }


  public void setCleansedDescription(String cleansedDescription) {
    this.cleansedDescription = cleansedDescription;
  }


  public Enrichment merchant(EnrichmentMerchant merchant) {
    
    this.merchant = merchant;
    return this;
  }

   /**
   * Get merchant
   * @return merchant
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EnrichmentMerchant getMerchant() {
    return merchant;
  }


  public void setMerchant(EnrichmentMerchant merchant) {
    this.merchant = merchant;
  }


  public Enrichment location(String location) {
    
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLocation() {
    return location;
  }


  public void setLocation(String location) {
    this.location = location;
  }


  public Enrichment paymentProcessor(String paymentProcessor) {
    
    this.paymentProcessor = paymentProcessor;
    return this;
  }

   /**
   * Get paymentProcessor
   * @return paymentProcessor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPaymentProcessor() {
    return paymentProcessor;
  }


  public void setPaymentProcessor(String paymentProcessor) {
    this.paymentProcessor = paymentProcessor;
  }


  public Enrichment correctedDate(OffsetDateTime correctedDate) {
    
    this.correctedDate = correctedDate;
    return this;
  }

   /**
   * Get correctedDate
   * @return correctedDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getCorrectedDate() {
    return correctedDate;
  }


  public void setCorrectedDate(OffsetDateTime correctedDate) {
    this.correctedDate = correctedDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Enrichment enrichment = (Enrichment) o;
    return Objects.equals(this.categorisation, enrichment.categorisation) &&
        Objects.equals(this.transactionHash, enrichment.transactionHash) &&
        Objects.equals(this.cleansedDescription, enrichment.cleansedDescription) &&
        Objects.equals(this.merchant, enrichment.merchant) &&
        Objects.equals(this.location, enrichment.location) &&
        Objects.equals(this.paymentProcessor, enrichment.paymentProcessor) &&
        Objects.equals(this.correctedDate, enrichment.correctedDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(categorisation, transactionHash, cleansedDescription, merchant, location, paymentProcessor, correctedDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Enrichment {\n");
    sb.append("    categorisation: ").append(toIndentedString(categorisation)).append("\n");
    sb.append("    transactionHash: ").append(toIndentedString(transactionHash)).append("\n");
    sb.append("    cleansedDescription: ").append(toIndentedString(cleansedDescription)).append("\n");
    sb.append("    merchant: ").append(toIndentedString(merchant)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    paymentProcessor: ").append(toIndentedString(paymentProcessor)).append("\n");
    sb.append("    correctedDate: ").append(toIndentedString(correctedDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

