/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.14.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.ob.domain.yapilymodels;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Detailed information regarding the issue that was experienced during processing of the request
 */
@ApiModel(description = "Detailed information regarding the issue that was experienced during processing of the request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-16T14:42:32.575816279Z[Europe/London]")
public class ErrorIssue {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private String code;

  public static final String SERIALIZED_NAME_PARAMETER = "parameter";
  @SerializedName(SERIALIZED_NAME_PARAMETER)
  private String parameter;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_INSTITUTION_ERROR = "institutionError";
  @SerializedName(SERIALIZED_NAME_INSTITUTION_ERROR)
  private InstitutionError institutionError;

  public ErrorIssue() { 
  }

  public ErrorIssue type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Category of the issue
   * @return type
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Category of the issue")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public ErrorIssue code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * Code that uniquely identifies the type of issue
   * @return code
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Code that uniquely identifies the type of issue")

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public ErrorIssue parameter(String parameter) {
    
    this.parameter = parameter;
    return this;
  }

   /**
   * Identfies the parameter / property within the request (headers, query parameters or body) that the issue relates to. For headers and query parameters, it refers to the parameter name. For the body, it refers to the JSONPath of the property
   * @return parameter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Identfies the parameter / property within the request (headers, query parameters or body) that the issue relates to. For headers and query parameters, it refers to the parameter name. For the body, it refers to the JSONPath of the property")

  public String getParameter() {
    return parameter;
  }


  public void setParameter(String parameter) {
    this.parameter = parameter;
  }


  public ErrorIssue message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * Human readable description of the issue that was experienced
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Human readable description of the issue that was experienced")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  public ErrorIssue institutionError(InstitutionError institutionError) {
    
    this.institutionError = institutionError;
    return this;
  }

   /**
   * Get institutionError
   * @return institutionError
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public InstitutionError getInstitutionError() {
    return institutionError;
  }


  public void setInstitutionError(InstitutionError institutionError) {
    this.institutionError = institutionError;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorIssue errorIssue = (ErrorIssue) o;
    return Objects.equals(this.type, errorIssue.type) &&
        Objects.equals(this.code, errorIssue.code) &&
        Objects.equals(this.parameter, errorIssue.parameter) &&
        Objects.equals(this.message, errorIssue.message) &&
        Objects.equals(this.institutionError, errorIssue.institutionError);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, code, parameter, message, institutionError);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorIssue {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    parameter: ").append(toIndentedString(parameter)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    institutionError: ").append(toIndentedString(institutionError)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

