/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.14.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.ob.domain.yapilymodels;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

/**
 * MultiAuthorisation
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-16T14:42:32.575816279Z[Europe/London]")
public class MultiAuthorisation {
  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_NUMBER_OF_AUTHORISATION_REQUIRED = "numberOfAuthorisationRequired";
  @SerializedName(SERIALIZED_NAME_NUMBER_OF_AUTHORISATION_REQUIRED)
  private Integer numberOfAuthorisationRequired;

  public static final String SERIALIZED_NAME_NUMBER_OF_AUTHORISATION_RECEIVED = "numberOfAuthorisationReceived";
  @SerializedName(SERIALIZED_NAME_NUMBER_OF_AUTHORISATION_RECEIVED)
  private Integer numberOfAuthorisationReceived;

  public static final String SERIALIZED_NAME_LAST_UPDATED_DATE_TIME = "lastUpdatedDateTime";
  @SerializedName(SERIALIZED_NAME_LAST_UPDATED_DATE_TIME)
  private OffsetDateTime lastUpdatedDateTime;

  public static final String SERIALIZED_NAME_EXPIRATION_DATE_TIME = "expirationDateTime";
  @SerializedName(SERIALIZED_NAME_EXPIRATION_DATE_TIME)
  private OffsetDateTime expirationDateTime;

  public MultiAuthorisation() { 
  }

  public MultiAuthorisation status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public MultiAuthorisation numberOfAuthorisationRequired(Integer numberOfAuthorisationRequired) {
    
    this.numberOfAuthorisationRequired = numberOfAuthorisationRequired;
    return this;
  }

   /**
   * Get numberOfAuthorisationRequired
   * @return numberOfAuthorisationRequired
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getNumberOfAuthorisationRequired() {
    return numberOfAuthorisationRequired;
  }


  public void setNumberOfAuthorisationRequired(Integer numberOfAuthorisationRequired) {
    this.numberOfAuthorisationRequired = numberOfAuthorisationRequired;
  }


  public MultiAuthorisation numberOfAuthorisationReceived(Integer numberOfAuthorisationReceived) {
    
    this.numberOfAuthorisationReceived = numberOfAuthorisationReceived;
    return this;
  }

   /**
   * Get numberOfAuthorisationReceived
   * @return numberOfAuthorisationReceived
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getNumberOfAuthorisationReceived() {
    return numberOfAuthorisationReceived;
  }


  public void setNumberOfAuthorisationReceived(Integer numberOfAuthorisationReceived) {
    this.numberOfAuthorisationReceived = numberOfAuthorisationReceived;
  }


  public MultiAuthorisation lastUpdatedDateTime(OffsetDateTime lastUpdatedDateTime) {
    
    this.lastUpdatedDateTime = lastUpdatedDateTime;
    return this;
  }

   /**
   * Get lastUpdatedDateTime
   * @return lastUpdatedDateTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getLastUpdatedDateTime() {
    return lastUpdatedDateTime;
  }


  public void setLastUpdatedDateTime(OffsetDateTime lastUpdatedDateTime) {
    this.lastUpdatedDateTime = lastUpdatedDateTime;
  }


  public MultiAuthorisation expirationDateTime(OffsetDateTime expirationDateTime) {
    
    this.expirationDateTime = expirationDateTime;
    return this;
  }

   /**
   * Get expirationDateTime
   * @return expirationDateTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getExpirationDateTime() {
    return expirationDateTime;
  }


  public void setExpirationDateTime(OffsetDateTime expirationDateTime) {
    this.expirationDateTime = expirationDateTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultiAuthorisation multiAuthorisation = (MultiAuthorisation) o;
    return Objects.equals(this.status, multiAuthorisation.status) &&
        Objects.equals(this.numberOfAuthorisationRequired, multiAuthorisation.numberOfAuthorisationRequired) &&
        Objects.equals(this.numberOfAuthorisationReceived, multiAuthorisation.numberOfAuthorisationReceived) &&
        Objects.equals(this.lastUpdatedDateTime, multiAuthorisation.lastUpdatedDateTime) &&
        Objects.equals(this.expirationDateTime, multiAuthorisation.expirationDateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, numberOfAuthorisationRequired, numberOfAuthorisationReceived, lastUpdatedDateTime, expirationDateTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultiAuthorisation {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    numberOfAuthorisationRequired: ").append(toIndentedString(numberOfAuthorisationRequired)).append("\n");
    sb.append("    numberOfAuthorisationReceived: ").append(toIndentedString(numberOfAuthorisationReceived)).append("\n");
    sb.append("    lastUpdatedDateTime: ").append(toIndentedString(lastUpdatedDateTime)).append("\n");
    sb.append("    expirationDateTime: ").append(toIndentedString(expirationDateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

