/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.14.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.ob.domain.yapilymodels;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.util.*;

/**
 * PaymentAuthorisationRequestResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-16T14:42:32.575816279Z[Europe/London]")
public class PaymentAuthorisationRequestResponse {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_USER_UUID = "userUuid";
  @SerializedName(SERIALIZED_NAME_USER_UUID)
  private UUID userUuid;

  public static final String SERIALIZED_NAME_APPLICATION_USER_ID = "applicationUserId";
  @SerializedName(SERIALIZED_NAME_APPLICATION_USER_ID)
  private String applicationUserId;

  public static final String SERIALIZED_NAME_REFERENCE_ID = "referenceId";
  @SerializedName(SERIALIZED_NAME_REFERENCE_ID)
  private String referenceId;

  public static final String SERIALIZED_NAME_INSTITUTION_ID = "institutionId";
  @SerializedName(SERIALIZED_NAME_INSTITUTION_ID)
  private String institutionId;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private AuthorisationStatus status;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_TRANSACTION_FROM = "transactionFrom";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_FROM)
  private OffsetDateTime transactionFrom;

  public static final String SERIALIZED_NAME_TRANSACTION_TO = "transactionTo";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_TO)
  private OffsetDateTime transactionTo;

  public static final String SERIALIZED_NAME_EXPIRES_AT = "expiresAt";
  @SerializedName(SERIALIZED_NAME_EXPIRES_AT)
  private OffsetDateTime expiresAt;

  public static final String SERIALIZED_NAME_TIME_TO_EXPIRE_IN_MILLIS = "timeToExpireInMillis";
  @SerializedName(SERIALIZED_NAME_TIME_TO_EXPIRE_IN_MILLIS)
  private Long timeToExpireInMillis;

  public static final String SERIALIZED_NAME_TIME_TO_EXPIRE = "timeToExpire";
  @SerializedName(SERIALIZED_NAME_TIME_TO_EXPIRE)
  private String timeToExpire;

  public static final String SERIALIZED_NAME_FEATURE_SCOPE = "featureScope";
  @SerializedName(SERIALIZED_NAME_FEATURE_SCOPE)
  private Set<FeatureEnum> featureScope = null;

  public static final String SERIALIZED_NAME_CONSENT_TOKEN = "consentToken";
  @SerializedName(SERIALIZED_NAME_CONSENT_TOKEN)
  private String consentToken;

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  private String state;

  public static final String SERIALIZED_NAME_AUTHORIZED_AT = "authorizedAt";
  @SerializedName(SERIALIZED_NAME_AUTHORIZED_AT)
  private OffsetDateTime authorizedAt;

  public static final String SERIALIZED_NAME_INSTITUTION_CONSENT_ID = "institutionConsentId";
  @SerializedName(SERIALIZED_NAME_INSTITUTION_CONSENT_ID)
  private String institutionConsentId;

  public static final String SERIALIZED_NAME_CHARGES = "charges";
  @SerializedName(SERIALIZED_NAME_CHARGES)
  private List<PaymentChargeDetails> charges = null;

  public static final String SERIALIZED_NAME_EXCHANGE_RATE_INFORMATION = "exchangeRateInformation";
  @SerializedName(SERIALIZED_NAME_EXCHANGE_RATE_INFORMATION)
  private ExchangeRateInformationResponse exchangeRateInformation;

  public static final String SERIALIZED_NAME_AUTHORISATION_URL = "authorisationUrl";
  @SerializedName(SERIALIZED_NAME_AUTHORISATION_URL)
  private String authorisationUrl;

  public static final String SERIALIZED_NAME_QR_CODE_URL = "qrCodeUrl";
  @SerializedName(SERIALIZED_NAME_QR_CODE_URL)
  private String qrCodeUrl;

  public static final String SERIALIZED_NAME_EXPLANATION = "explanation";
  @SerializedName(SERIALIZED_NAME_EXPLANATION)
  private String explanation;

  public PaymentAuthorisationRequestResponse() { 
  }

  public PaymentAuthorisationRequestResponse id(UUID id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UUID getId() {
    return id;
  }


  public void setId(UUID id) {
    this.id = id;
  }


  public PaymentAuthorisationRequestResponse userUuid(UUID userUuid) {
    
    this.userUuid = userUuid;
    return this;
  }

   /**
   * Get userUuid
   * @return userUuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UUID getUserUuid() {
    return userUuid;
  }


  public void setUserUuid(UUID userUuid) {
    this.userUuid = userUuid;
  }


  public PaymentAuthorisationRequestResponse applicationUserId(String applicationUserId) {
    
    this.applicationUserId = applicationUserId;
    return this;
  }

   /**
   * Get applicationUserId
   * @return applicationUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getApplicationUserId() {
    return applicationUserId;
  }


  public void setApplicationUserId(String applicationUserId) {
    this.applicationUserId = applicationUserId;
  }


  public PaymentAuthorisationRequestResponse referenceId(String referenceId) {
    
    this.referenceId = referenceId;
    return this;
  }

   /**
   * Get referenceId
   * @return referenceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getReferenceId() {
    return referenceId;
  }


  public void setReferenceId(String referenceId) {
    this.referenceId = referenceId;
  }


  public PaymentAuthorisationRequestResponse institutionId(String institutionId) {
    
    this.institutionId = institutionId;
    return this;
  }

   /**
   * Get institutionId
   * @return institutionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getInstitutionId() {
    return institutionId;
  }


  public void setInstitutionId(String institutionId) {
    this.institutionId = institutionId;
  }


  public PaymentAuthorisationRequestResponse status(AuthorisationStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AuthorisationStatus getStatus() {
    return status;
  }


  public void setStatus(AuthorisationStatus status) {
    this.status = status;
  }


  public PaymentAuthorisationRequestResponse createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public PaymentAuthorisationRequestResponse transactionFrom(OffsetDateTime transactionFrom) {
    
    this.transactionFrom = transactionFrom;
    return this;
  }

   /**
   * Get transactionFrom
   * @return transactionFrom
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getTransactionFrom() {
    return transactionFrom;
  }


  public void setTransactionFrom(OffsetDateTime transactionFrom) {
    this.transactionFrom = transactionFrom;
  }


  public PaymentAuthorisationRequestResponse transactionTo(OffsetDateTime transactionTo) {
    
    this.transactionTo = transactionTo;
    return this;
  }

   /**
   * Get transactionTo
   * @return transactionTo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getTransactionTo() {
    return transactionTo;
  }


  public void setTransactionTo(OffsetDateTime transactionTo) {
    this.transactionTo = transactionTo;
  }


  public PaymentAuthorisationRequestResponse expiresAt(OffsetDateTime expiresAt) {
    
    this.expiresAt = expiresAt;
    return this;
  }

   /**
   * Get expiresAt
   * @return expiresAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }


  public void setExpiresAt(OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }


  public PaymentAuthorisationRequestResponse timeToExpireInMillis(Long timeToExpireInMillis) {
    
    this.timeToExpireInMillis = timeToExpireInMillis;
    return this;
  }

   /**
   * Get timeToExpireInMillis
   * @return timeToExpireInMillis
   * @deprecated
  **/
  @Deprecated
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getTimeToExpireInMillis() {
    return timeToExpireInMillis;
  }


  public void setTimeToExpireInMillis(Long timeToExpireInMillis) {
    this.timeToExpireInMillis = timeToExpireInMillis;
  }


  public PaymentAuthorisationRequestResponse timeToExpire(String timeToExpire) {
    
    this.timeToExpire = timeToExpire;
    return this;
  }

   /**
   * Get timeToExpire
   * @return timeToExpire
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTimeToExpire() {
    return timeToExpire;
  }


  public void setTimeToExpire(String timeToExpire) {
    this.timeToExpire = timeToExpire;
  }


  public PaymentAuthorisationRequestResponse featureScope(Set<FeatureEnum> featureScope) {
    
    this.featureScope = featureScope;
    return this;
  }

  public PaymentAuthorisationRequestResponse addFeatureScopeItem(FeatureEnum featureScopeItem) {
    if (this.featureScope == null) {
      this.featureScope = new LinkedHashSet<FeatureEnum>();
    }
    this.featureScope.add(featureScopeItem);
    return this;
  }

   /**
   * Get featureScope
   * @return featureScope
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Set<FeatureEnum> getFeatureScope() {
    return featureScope;
  }


  public void setFeatureScope(Set<FeatureEnum> featureScope) {
    this.featureScope = featureScope;
  }


  public PaymentAuthorisationRequestResponse consentToken(String consentToken) {
    
    this.consentToken = consentToken;
    return this;
  }

   /**
   * Get consentToken
   * @return consentToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getConsentToken() {
    return consentToken;
  }


  public void setConsentToken(String consentToken) {
    this.consentToken = consentToken;
  }


  public PaymentAuthorisationRequestResponse state(String state) {
    
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getState() {
    return state;
  }


  public void setState(String state) {
    this.state = state;
  }


  public PaymentAuthorisationRequestResponse authorizedAt(OffsetDateTime authorizedAt) {
    
    this.authorizedAt = authorizedAt;
    return this;
  }

   /**
   * Get authorizedAt
   * @return authorizedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getAuthorizedAt() {
    return authorizedAt;
  }


  public void setAuthorizedAt(OffsetDateTime authorizedAt) {
    this.authorizedAt = authorizedAt;
  }


  public PaymentAuthorisationRequestResponse institutionConsentId(String institutionConsentId) {
    
    this.institutionConsentId = institutionConsentId;
    return this;
  }

   /**
   * Get institutionConsentId
   * @return institutionConsentId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getInstitutionConsentId() {
    return institutionConsentId;
  }


  public void setInstitutionConsentId(String institutionConsentId) {
    this.institutionConsentId = institutionConsentId;
  }


  public PaymentAuthorisationRequestResponse charges(List<PaymentChargeDetails> charges) {
    
    this.charges = charges;
    return this;
  }

  public PaymentAuthorisationRequestResponse addChargesItem(PaymentChargeDetails chargesItem) {
    if (this.charges == null) {
      this.charges = new ArrayList<PaymentChargeDetails>();
    }
    this.charges.add(chargesItem);
    return this;
  }

   /**
   * Get charges
   * @return charges
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<PaymentChargeDetails> getCharges() {
    return charges;
  }


  public void setCharges(List<PaymentChargeDetails> charges) {
    this.charges = charges;
  }


  public PaymentAuthorisationRequestResponse exchangeRateInformation(ExchangeRateInformationResponse exchangeRateInformation) {
    
    this.exchangeRateInformation = exchangeRateInformation;
    return this;
  }

   /**
   * Get exchangeRateInformation
   * @return exchangeRateInformation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ExchangeRateInformationResponse getExchangeRateInformation() {
    return exchangeRateInformation;
  }


  public void setExchangeRateInformation(ExchangeRateInformationResponse exchangeRateInformation) {
    this.exchangeRateInformation = exchangeRateInformation;
  }


  public PaymentAuthorisationRequestResponse authorisationUrl(String authorisationUrl) {
    
    this.authorisationUrl = authorisationUrl;
    return this;
  }

   /**
   * Get authorisationUrl
   * @return authorisationUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAuthorisationUrl() {
    return authorisationUrl;
  }


  public void setAuthorisationUrl(String authorisationUrl) {
    this.authorisationUrl = authorisationUrl;
  }


  public PaymentAuthorisationRequestResponse qrCodeUrl(String qrCodeUrl) {
    
    this.qrCodeUrl = qrCodeUrl;
    return this;
  }

   /**
   * Get qrCodeUrl
   * @return qrCodeUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getQrCodeUrl() {
    return qrCodeUrl;
  }


  public void setQrCodeUrl(String qrCodeUrl) {
    this.qrCodeUrl = qrCodeUrl;
  }


  public PaymentAuthorisationRequestResponse explanation(String explanation) {
    
    this.explanation = explanation;
    return this;
  }

   /**
   * Get explanation
   * @return explanation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getExplanation() {
    return explanation;
  }


  public void setExplanation(String explanation) {
    this.explanation = explanation;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentAuthorisationRequestResponse paymentAuthorisationRequestResponse = (PaymentAuthorisationRequestResponse) o;
    return Objects.equals(this.id, paymentAuthorisationRequestResponse.id) &&
        Objects.equals(this.userUuid, paymentAuthorisationRequestResponse.userUuid) &&
        Objects.equals(this.applicationUserId, paymentAuthorisationRequestResponse.applicationUserId) &&
        Objects.equals(this.referenceId, paymentAuthorisationRequestResponse.referenceId) &&
        Objects.equals(this.institutionId, paymentAuthorisationRequestResponse.institutionId) &&
        Objects.equals(this.status, paymentAuthorisationRequestResponse.status) &&
        Objects.equals(this.createdAt, paymentAuthorisationRequestResponse.createdAt) &&
        Objects.equals(this.transactionFrom, paymentAuthorisationRequestResponse.transactionFrom) &&
        Objects.equals(this.transactionTo, paymentAuthorisationRequestResponse.transactionTo) &&
        Objects.equals(this.expiresAt, paymentAuthorisationRequestResponse.expiresAt) &&
        Objects.equals(this.timeToExpireInMillis, paymentAuthorisationRequestResponse.timeToExpireInMillis) &&
        Objects.equals(this.timeToExpire, paymentAuthorisationRequestResponse.timeToExpire) &&
        Objects.equals(this.featureScope, paymentAuthorisationRequestResponse.featureScope) &&
        Objects.equals(this.consentToken, paymentAuthorisationRequestResponse.consentToken) &&
        Objects.equals(this.state, paymentAuthorisationRequestResponse.state) &&
        Objects.equals(this.authorizedAt, paymentAuthorisationRequestResponse.authorizedAt) &&
        Objects.equals(this.institutionConsentId, paymentAuthorisationRequestResponse.institutionConsentId) &&
        Objects.equals(this.charges, paymentAuthorisationRequestResponse.charges) &&
        Objects.equals(this.exchangeRateInformation, paymentAuthorisationRequestResponse.exchangeRateInformation) &&
        Objects.equals(this.authorisationUrl, paymentAuthorisationRequestResponse.authorisationUrl) &&
        Objects.equals(this.qrCodeUrl, paymentAuthorisationRequestResponse.qrCodeUrl) &&
        Objects.equals(this.explanation, paymentAuthorisationRequestResponse.explanation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, userUuid, applicationUserId, referenceId, institutionId, status, createdAt, transactionFrom, transactionTo, expiresAt, timeToExpireInMillis, timeToExpire, featureScope, consentToken, state, authorizedAt, institutionConsentId, charges, exchangeRateInformation, authorisationUrl, qrCodeUrl, explanation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentAuthorisationRequestResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userUuid: ").append(toIndentedString(userUuid)).append("\n");
    sb.append("    applicationUserId: ").append(toIndentedString(applicationUserId)).append("\n");
    sb.append("    referenceId: ").append(toIndentedString(referenceId)).append("\n");
    sb.append("    institutionId: ").append(toIndentedString(institutionId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    transactionFrom: ").append(toIndentedString(transactionFrom)).append("\n");
    sb.append("    transactionTo: ").append(toIndentedString(transactionTo)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    timeToExpireInMillis: ").append(toIndentedString(timeToExpireInMillis)).append("\n");
    sb.append("    timeToExpire: ").append(toIndentedString(timeToExpire)).append("\n");
    sb.append("    featureScope: ").append(toIndentedString(featureScope)).append("\n");
    sb.append("    consentToken: ").append(toIndentedString(consentToken)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    authorizedAt: ").append(toIndentedString(authorizedAt)).append("\n");
    sb.append("    institutionConsentId: ").append(toIndentedString(institutionConsentId)).append("\n");
    sb.append("    charges: ").append(toIndentedString(charges)).append("\n");
    sb.append("    exchangeRateInformation: ").append(toIndentedString(exchangeRateInformation)).append("\n");
    sb.append("    authorisationUrl: ").append(toIndentedString(authorisationUrl)).append("\n");
    sb.append("    qrCodeUrl: ").append(toIndentedString(qrCodeUrl)).append("\n");
    sb.append("    explanation: ").append(toIndentedString(explanation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

