/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.14.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.ob.domain.yapilymodels;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;
import java.util.UUID;

/**
 * Object returned when creating a User Profile.
 */
@ApiModel(description = "Object returned when creating a User Profile.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-16T14:42:32.575816279Z[Europe/London]")
public class ProfileConsent {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private UUID userId;

  public static final String SERIALIZED_NAME_REFERENCE_CONSENT_ID = "referenceConsentId";
  @SerializedName(SERIALIZED_NAME_REFERENCE_CONSENT_ID)
  private UUID referenceConsentId;

  public static final String SERIALIZED_NAME_INSTITUTION_ID = "institutionId";
  @SerializedName(SERIALIZED_NAME_INSTITUTION_ID)
  private String institutionId;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_EXPIRES_AT = "expiresAt";
  @SerializedName(SERIALIZED_NAME_EXPIRES_AT)
  private OffsetDateTime expiresAt;

  public static final String SERIALIZED_NAME_DATA_INSERTED_AT = "dataInsertedAt";
  @SerializedName(SERIALIZED_NAME_DATA_INSERTED_AT)
  private OffsetDateTime dataInsertedAt;

  public ProfileConsent() { 
  }

  public ProfileConsent id(UUID id) {
    
    this.id = id;
    return this;
  }

   /**
   * The id of the ProfileConsent
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "eb2ad083-a111-4143-8756-a3a3cef4031c", value = "The id of the ProfileConsent")

  public UUID getId() {
    return id;
  }


  public void setId(UUID id) {
    this.id = id;
  }


  public ProfileConsent status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * The status, can be PENDING, COMPLETED or ERROR.
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "PENDING", value = "The status, can be PENDING, COMPLETED or ERROR.")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public ProfileConsent userId(UUID userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * The userUuid.
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "3ddf5dd0-aa48-4d0f-baa7-fa057e9e911d", value = "The userUuid.")

  public UUID getUserId() {
    return userId;
  }


  public void setUserId(UUID userId) {
    this.userId = userId;
  }


  public ProfileConsent referenceConsentId(UUID referenceConsentId) {
    
    this.referenceConsentId = referenceConsentId;
    return this;
  }

   /**
   * The referenceConsentId.
   * @return referenceConsentId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1e2e5167-8519-4c19-b016-8f2f0c6e38b6", value = "The referenceConsentId.")

  public UUID getReferenceConsentId() {
    return referenceConsentId;
  }


  public void setReferenceConsentId(UUID referenceConsentId) {
    this.referenceConsentId = referenceConsentId;
  }


  public ProfileConsent institutionId(String institutionId) {
    
    this.institutionId = institutionId;
    return this;
  }

   /**
   * The id of the Institution.
   * @return institutionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "mock-sandbox", value = "The id of the Institution.")

  public String getInstitutionId() {
    return institutionId;
  }


  public void setInstitutionId(String institutionId) {
    this.institutionId = institutionId;
  }


  public ProfileConsent createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * When a profile consent is created.
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "When a profile consent is created.")

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public ProfileConsent expiresAt(OffsetDateTime expiresAt) {
    
    this.expiresAt = expiresAt;
    return this;
  }

   /**
   * When a profile consent is expired after created + X.
   * @return expiresAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "When a profile consent is expired after created + X.")

  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }


  public void setExpiresAt(OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }


  public ProfileConsent dataInsertedAt(OffsetDateTime dataInsertedAt) {
    
    this.dataInsertedAt = dataInsertedAt;
    return this;
  }

   /**
   * After data retrieval from aggregated profile consent is completed.
   * @return dataInsertedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "After data retrieval from aggregated profile consent is completed.")

  public OffsetDateTime getDataInsertedAt() {
    return dataInsertedAt;
  }


  public void setDataInsertedAt(OffsetDateTime dataInsertedAt) {
    this.dataInsertedAt = dataInsertedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfileConsent profileConsent = (ProfileConsent) o;
    return Objects.equals(this.id, profileConsent.id) &&
        Objects.equals(this.status, profileConsent.status) &&
        Objects.equals(this.userId, profileConsent.userId) &&
        Objects.equals(this.referenceConsentId, profileConsent.referenceConsentId) &&
        Objects.equals(this.institutionId, profileConsent.institutionId) &&
        Objects.equals(this.createdAt, profileConsent.createdAt) &&
        Objects.equals(this.expiresAt, profileConsent.expiresAt) &&
        Objects.equals(this.dataInsertedAt, profileConsent.dataInsertedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, status, userId, referenceConsentId, institutionId, createdAt, expiresAt, dataInsertedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfileConsent {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    referenceConsentId: ").append(toIndentedString(referenceConsentId)).append("\n");
    sb.append("    institutionId: ").append(toIndentedString(institutionId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    dataInsertedAt: ").append(toIndentedString(dataInsertedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

