/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.14.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.ob.domain.yapilymodels;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.LinkedHashSet;
import java.util.Objects;
import java.util.Set;

/**
 * VirtualAccountBeneficiaryAccount
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-16T14:42:32.575816279Z[Europe/London]")
public class VirtualAccountBeneficiaryAccount {
  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private String currency;

  public static final String SERIALIZED_NAME_BANK_NAME = "bankName";
  @SerializedName(SERIALIZED_NAME_BANK_NAME)
  private String bankName;

  public static final String SERIALIZED_NAME_BANK_ADDRESS = "bankAddress";
  @SerializedName(SERIALIZED_NAME_BANK_ADDRESS)
  private String bankAddress;

  public static final String SERIALIZED_NAME_BANK_COUNTRY = "bankCountry";
  @SerializedName(SERIALIZED_NAME_BANK_COUNTRY)
  private String bankCountry;

  public static final String SERIALIZED_NAME_ACCOUNT_IDENTIFICATIONS = "accountIdentifications";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_IDENTIFICATIONS)
  private Set<AccountIdentification> accountIdentifications = new LinkedHashSet<AccountIdentification>();

  public VirtualAccountBeneficiaryAccount() { 
  }

  public VirtualAccountBeneficiaryAccount currency(String currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * Three-letter ISO 4217 currency code
   * @return currency
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "GBP", required = true, value = "Three-letter ISO 4217 currency code")

  public String getCurrency() {
    return currency;
  }


  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public VirtualAccountBeneficiaryAccount bankName(String bankName) {
    
    this.bankName = bankName;
    return this;
  }

   /**
   * Get bankName
   * @return bankName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lloyds Bank", value = "")

  public String getBankName() {
    return bankName;
  }


  public void setBankName(String bankName) {
    this.bankName = bankName;
  }


  public VirtualAccountBeneficiaryAccount bankAddress(String bankAddress) {
    
    this.bankAddress = bankAddress;
    return this;
  }

   /**
   * Get bankAddress
   * @return bankAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "WE12 ABC", value = "")

  public String getBankAddress() {
    return bankAddress;
  }


  public void setBankAddress(String bankAddress) {
    this.bankAddress = bankAddress;
  }


  public VirtualAccountBeneficiaryAccount bankCountry(String bankCountry) {
    
    this.bankCountry = bankCountry;
    return this;
  }

   /**
   * Two-letter ISO 3166 country code
   * @return bankCountry
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "GB", value = "Two-letter ISO 3166 country code")

  public String getBankCountry() {
    return bankCountry;
  }


  public void setBankCountry(String bankCountry) {
    this.bankCountry = bankCountry;
  }


  public VirtualAccountBeneficiaryAccount accountIdentifications(Set<AccountIdentification> accountIdentifications) {
    
    this.accountIdentifications = accountIdentifications;
    return this;
  }

  public VirtualAccountBeneficiaryAccount addAccountIdentificationsItem(AccountIdentification accountIdentificationsItem) {
    this.accountIdentifications.add(accountIdentificationsItem);
    return this;
  }

   /**
   * The account identifications that identify the Beneficiary bank account.
   * @return accountIdentifications
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "[{\"identification\":\"401016\",\"type\":\"SORT_CODE\"},{\"identification\":\"71518920\",\"type\":\"ACCOUNT_NUMBER\"}]", required = true, value = "The account identifications that identify the Beneficiary bank account.")

  public Set<AccountIdentification> getAccountIdentifications() {
    return accountIdentifications;
  }


  public void setAccountIdentifications(Set<AccountIdentification> accountIdentifications) {
    this.accountIdentifications = accountIdentifications;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VirtualAccountBeneficiaryAccount virtualAccountBeneficiaryAccount = (VirtualAccountBeneficiaryAccount) o;
    return Objects.equals(this.currency, virtualAccountBeneficiaryAccount.currency) &&
        Objects.equals(this.bankName, virtualAccountBeneficiaryAccount.bankName) &&
        Objects.equals(this.bankAddress, virtualAccountBeneficiaryAccount.bankAddress) &&
        Objects.equals(this.bankCountry, virtualAccountBeneficiaryAccount.bankCountry) &&
        Objects.equals(this.accountIdentifications, virtualAccountBeneficiaryAccount.accountIdentifications);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currency, bankName, bankAddress, bankCountry, accountIdentifications);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VirtualAccountBeneficiaryAccount {\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    bankName: ").append(toIndentedString(bankName)).append("\n");
    sb.append("    bankAddress: ").append(toIndentedString(bankAddress)).append("\n");
    sb.append("    bankCountry: ").append(toIndentedString(bankCountry)).append("\n");
    sb.append("    accountIdentifications: ").append(toIndentedString(accountIdentifications)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

