/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.14.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.starter.domain.yapilymodels;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Provides details of the error that has occured.
 */
@ApiModel(description = "Provides details of the error that has occured.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-16T14:42:32.575816279Z[Europe/London]")
public class ApiError {
  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private Integer code;

  public static final String SERIALIZED_NAME_INSTITUTION_ERROR = "institutionError";
  @SerializedName(SERIALIZED_NAME_INSTITUTION_ERROR)
  private InstitutionError institutionError;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_SOURCE = "source";
  @SerializedName(SERIALIZED_NAME_SOURCE)
  private String source;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_TRACING_ID = "tracingId";
  @SerializedName(SERIALIZED_NAME_TRACING_ID)
  private String tracingId;

  public ApiError() { 
  }

  public ApiError code(Integer code) {
    
    this.code = code;
    return this;
  }

   /**
   * _Mandatory_. Numeric &#x60;HTTP&#x60; status code associated with the error.
   * @return code
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "_Mandatory_. Numeric `HTTP` status code associated with the error.")

  public Integer getCode() {
    return code;
  }


  public void setCode(Integer code) {
    this.code = code;
  }


  public ApiError institutionError(InstitutionError institutionError) {
    
    this.institutionError = institutionError;
    return this;
  }

   /**
   * Get institutionError
   * @return institutionError
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public InstitutionError getInstitutionError() {
    return institutionError;
  }


  public void setInstitutionError(InstitutionError institutionError) {
    this.institutionError = institutionError;
  }


  public ApiError message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * __Mandatory__. Description of the exact error that has been experienced.
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "__Mandatory__. Description of the exact error that has been experienced.")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  public ApiError source(String source) {
    
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSource() {
    return source;
  }


  public void setSource(String source) {
    this.source = source;
  }


  public ApiError status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * __Mandatory__. Textual description of the &#x60;HTTP&#x60; error status type.
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "__Mandatory__. Textual description of the `HTTP` error status type.")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public ApiError tracingId(String tracingId) {
    
    this.tracingId = tracingId;
    return this;
  }

   /**
   * _Optional_.  A unique identifier assigned by Yapily for the request that can be used for support purposes.
   * @return tracingId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "_Optional_.  A unique identifier assigned by Yapily for the request that can be used for support purposes.")

  public String getTracingId() {
    return tracingId;
  }


  public void setTracingId(String tracingId) {
    this.tracingId = tracingId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiError apiError = (ApiError) o;
    return Objects.equals(this.code, apiError.code) &&
        Objects.equals(this.institutionError, apiError.institutionError) &&
        Objects.equals(this.message, apiError.message) &&
        Objects.equals(this.source, apiError.source) &&
        Objects.equals(this.status, apiError.status) &&
        Objects.equals(this.tracingId, apiError.tracingId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, institutionError, message, source, status, tracingId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiError {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    institutionError: ").append(toIndentedString(institutionError)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tracingId: ").append(toIndentedString(tracingId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

