/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.14.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.starter.domain.yapilymodels;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.LinkedHashSet;
import java.util.Objects;
import java.util.Set;

/**
 * __Mandatory__. The &#x60;BeneficiaryPayee&#x60; object contains details of the beneficiary [person or business]. You must define this in your payment request along with all of the nested mandatory properties.
 */
@ApiModel(description = "__Mandatory__. The `BeneficiaryPayee` object contains details of the beneficiary [person or business]. You must define this in your payment request along with all of the nested mandatory properties.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-16T14:42:32.575816279Z[Europe/London]")
public class BeneficiaryPayee {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_ACCOUNT_IDENTIFICATIONS = "accountIdentifications";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_IDENTIFICATIONS)
  private Set<AccountIdentification> accountIdentifications = new LinkedHashSet<AccountIdentification>();

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private Address address;

  public BeneficiaryPayee() { 
  }

  public BeneficiaryPayee name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The account holder name of the beneficiary.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Jane Doe", value = "The account holder name of the beneficiary.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public BeneficiaryPayee accountIdentifications(Set<AccountIdentification> accountIdentifications) {
    
    this.accountIdentifications = accountIdentifications;
    return this;
  }

  public BeneficiaryPayee addAccountIdentificationsItem(AccountIdentification accountIdentificationsItem) {
    this.accountIdentifications.add(accountIdentificationsItem);
    return this;
  }

   /**
   * __Mandatory__. The account identifications that identify the &#x60;BeneficiaryPayee&#x60; bank account.
   * @return accountIdentifications
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "[{\"identification\":\"401016\",\"type\":\"SORT_CODE\"},{\"identification\":\"71518920\",\"type\":\"ACCOUNT_NUMBER\"}]", required = true, value = "__Mandatory__. The account identifications that identify the `BeneficiaryPayee` bank account.")

  public Set<AccountIdentification> getAccountIdentifications() {
    return accountIdentifications;
  }


  public void setAccountIdentifications(Set<AccountIdentification> accountIdentifications) {
    this.accountIdentifications = accountIdentifications;
  }


  public BeneficiaryPayee address(Address address) {
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Address getAddress() {
    return address;
  }


  public void setAddress(Address address) {
    this.address = address;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BeneficiaryPayee beneficiaryPayee = (BeneficiaryPayee) o;
    return Objects.equals(this.name, beneficiaryPayee.name) &&
        Objects.equals(this.accountIdentifications, beneficiaryPayee.accountIdentifications) &&
        Objects.equals(this.address, beneficiaryPayee.address);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, accountIdentifications, address);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BeneficiaryPayee {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    accountIdentifications: ").append(toIndentedString(accountIdentifications)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

