/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.14.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.starter.domain.yapilymodels;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * The payment request object defining the details of the bulk payment
 */
@ApiModel(description = "The payment request object defining the details of the bulk payment")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-16T14:42:32.575816279Z[Europe/London]")
public class BulkPaymentRequest {
  public static final String SERIALIZED_NAME_PAYMENTS = "payments";
  @SerializedName(SERIALIZED_NAME_PAYMENTS)
  private List<PaymentRequest> payments = new ArrayList<PaymentRequest>();

  public static final String SERIALIZED_NAME_ORIGINATOR_IDENTIFICATION_NUMBER = "originatorIdentificationNumber";
  @SerializedName(SERIALIZED_NAME_ORIGINATOR_IDENTIFICATION_NUMBER)
  private String originatorIdentificationNumber;

  public static final String SERIALIZED_NAME_EXECUTION_DATE_TIME = "executionDateTime";
  @SerializedName(SERIALIZED_NAME_EXECUTION_DATE_TIME)
  private OffsetDateTime executionDateTime;

  public BulkPaymentRequest() { 
  }

  public BulkPaymentRequest payments(List<PaymentRequest> payments) {
    
    this.payments = payments;
    return this;
  }

  public BulkPaymentRequest addPaymentsItem(PaymentRequest paymentsItem) {
    this.payments.add(paymentsItem);
    return this;
  }

   /**
   * __Mandatory__. The array of &#x60;PaymentRequest&#x60; objects to initiate in the bulk payment.
   * @return payments
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "__Mandatory__. The array of `PaymentRequest` objects to initiate in the bulk payment.")

  public List<PaymentRequest> getPayments() {
    return payments;
  }


  public void setPayments(List<PaymentRequest> payments) {
    this.payments = payments;
  }


  public BulkPaymentRequest originatorIdentificationNumber(String originatorIdentificationNumber) {
    
    this.originatorIdentificationNumber = originatorIdentificationNumber;
    return this;
  }

   /**
   * __Conditional__. The identification number of the originator.&lt;ul&gt;&lt;li&gt;Mandatory for AIB bulk payments&lt;/li&gt;&lt;/ul&gt;
   * @return originatorIdentificationNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "__Conditional__. The identification number of the originator.<ul><li>Mandatory for AIB bulk payments</li></ul>")

  public String getOriginatorIdentificationNumber() {
    return originatorIdentificationNumber;
  }


  public void setOriginatorIdentificationNumber(String originatorIdentificationNumber) {
    this.originatorIdentificationNumber = originatorIdentificationNumber;
  }


  public BulkPaymentRequest executionDateTime(OffsetDateTime executionDateTime) {
    
    this.executionDateTime = executionDateTime;
    return this;
  }

   /**
   * __Optional__. Used to schedule the bulk payment to be executed at a future date if supported by the &#x60;Institution&#x60;.
   * @return executionDateTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "__Optional__. Used to schedule the bulk payment to be executed at a future date if supported by the `Institution`.")

  public OffsetDateTime getExecutionDateTime() {
    return executionDateTime;
  }


  public void setExecutionDateTime(OffsetDateTime executionDateTime) {
    this.executionDateTime = executionDateTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkPaymentRequest bulkPaymentRequest = (BulkPaymentRequest) o;
    return Objects.equals(this.payments, bulkPaymentRequest.payments) &&
        Objects.equals(this.originatorIdentificationNumber, bulkPaymentRequest.originatorIdentificationNumber) &&
        Objects.equals(this.executionDateTime, bulkPaymentRequest.executionDateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payments, originatorIdentificationNumber, executionDateTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkPaymentRequest {\n");
    sb.append("    payments: ").append(toIndentedString(payments)).append("\n");
    sb.append("    originatorIdentificationNumber: ").append(toIndentedString(originatorIdentificationNumber)).append("\n");
    sb.append("    executionDateTime: ").append(toIndentedString(executionDateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

