/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.14.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.starter.domain.yapilymodels;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

/**
 * ExtendConsentRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-16T14:42:32.575816279Z[Europe/London]")
public class ExtendConsentRequest {
  public static final String SERIALIZED_NAME_LAST_CONFIRMED_AT = "lastConfirmedAt";
  @SerializedName(SERIALIZED_NAME_LAST_CONFIRMED_AT)
  private OffsetDateTime lastConfirmedAt;

  public ExtendConsentRequest() { 
  }

  public ExtendConsentRequest lastConfirmedAt(OffsetDateTime lastConfirmedAt) {
    
    this.lastConfirmedAt = lastConfirmedAt;
    return this;
  }

   /**
   * __Mandatory__. The time that the user confirmed access to their account information
   * @return lastConfirmedAt
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "2022-08-16T10:59:53.288Z", required = true, value = "__Mandatory__. The time that the user confirmed access to their account information")

  public OffsetDateTime getLastConfirmedAt() {
    return lastConfirmedAt;
  }


  public void setLastConfirmedAt(OffsetDateTime lastConfirmedAt) {
    this.lastConfirmedAt = lastConfirmedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExtendConsentRequest extendConsentRequest = (ExtendConsentRequest) o;
    return Objects.equals(this.lastConfirmedAt, extendConsentRequest.lastConfirmedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastConfirmedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtendConsentRequest {\n");
    sb.append("    lastConfirmedAt: ").append(toIndentedString(lastConfirmedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

