/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.14.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.starter.domain.yapilymodels;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

/**
 * MonitoringEndpointStatus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-16T14:42:32.575816279Z[Europe/London]")
public class MonitoringEndpointStatus {
  public static final String SERIALIZED_NAME_LAST_TESTED = "lastTested";
  @SerializedName(SERIALIZED_NAME_LAST_TESTED)
  private OffsetDateTime lastTested;

  public static final String SERIALIZED_NAME_RESOURCE_ENDPOINT = "resourceEndpoint";
  @SerializedName(SERIALIZED_NAME_RESOURCE_ENDPOINT)
  private String resourceEndpoint;

  public static final String SERIALIZED_NAME_SPAN = "span";
  @SerializedName(SERIALIZED_NAME_SPAN)
  private String span;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private MonitoringStatusEnum status;

  public MonitoringEndpointStatus() { 
  }

  public MonitoringEndpointStatus lastTested(OffsetDateTime lastTested) {
    
    this.lastTested = lastTested;
    return this;
  }

   /**
   * Get lastTested
   * @return lastTested
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getLastTested() {
    return lastTested;
  }


  public void setLastTested(OffsetDateTime lastTested) {
    this.lastTested = lastTested;
  }


  public MonitoringEndpointStatus resourceEndpoint(String resourceEndpoint) {
    
    this.resourceEndpoint = resourceEndpoint;
    return this;
  }

   /**
   * Get resourceEndpoint
   * @return resourceEndpoint
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getResourceEndpoint() {
    return resourceEndpoint;
  }


  public void setResourceEndpoint(String resourceEndpoint) {
    this.resourceEndpoint = resourceEndpoint;
  }


  public MonitoringEndpointStatus span(String span) {
    
    this.span = span;
    return this;
  }

   /**
   * Get span
   * @return span
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSpan() {
    return span;
  }


  public void setSpan(String span) {
    this.span = span;
  }


  public MonitoringEndpointStatus status(MonitoringStatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MonitoringStatusEnum getStatus() {
    return status;
  }


  public void setStatus(MonitoringStatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MonitoringEndpointStatus monitoringEndpointStatus = (MonitoringEndpointStatus) o;
    return Objects.equals(this.lastTested, monitoringEndpointStatus.lastTested) &&
        Objects.equals(this.resourceEndpoint, monitoringEndpointStatus.resourceEndpoint) &&
        Objects.equals(this.span, monitoringEndpointStatus.span) &&
        Objects.equals(this.status, monitoringEndpointStatus.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastTested, resourceEndpoint, span, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MonitoringEndpointStatus {\n");
    sb.append("    lastTested: ").append(toIndentedString(lastTested)).append("\n");
    sb.append("    resourceEndpoint: ").append(toIndentedString(resourceEndpoint)).append("\n");
    sb.append("    span: ").append(toIndentedString(span)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

