/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.14.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.starter.domain.yapilymodels;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * PaymentResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-16T14:42:32.575816279Z[Europe/London]")
public class PaymentResponse {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_INSTITUTION_CONSENT_ID = "institutionConsentId";
  @SerializedName(SERIALIZED_NAME_INSTITUTION_CONSENT_ID)
  private String institutionConsentId;

  public static final String SERIALIZED_NAME_PAYMENT_IDEMPOTENCY_ID = "paymentIdempotencyId";
  @SerializedName(SERIALIZED_NAME_PAYMENT_IDEMPOTENCY_ID)
  private String paymentIdempotencyId;

  public static final String SERIALIZED_NAME_PAYMENT_LIFECYCLE_ID = "paymentLifecycleId";
  @SerializedName(SERIALIZED_NAME_PAYMENT_LIFECYCLE_ID)
  private String paymentLifecycleId;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private PaymentStatus status;

  public static final String SERIALIZED_NAME_STATUS_DETAILS = "statusDetails";
  @SerializedName(SERIALIZED_NAME_STATUS_DETAILS)
  private PaymentStatusDetails statusDetails;

  public static final String SERIALIZED_NAME_PAYER = "payer";
  @SerializedName(SERIALIZED_NAME_PAYER)
  private Payer payer;

  public static final String SERIALIZED_NAME_PAYEE_DETAILS = "payeeDetails";
  @SerializedName(SERIALIZED_NAME_PAYEE_DETAILS)
  private Payee payeeDetails;

  public static final String SERIALIZED_NAME_REFERENCE = "reference";
  @SerializedName(SERIALIZED_NAME_REFERENCE)
  private String reference;

  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private BigDecimal amount;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private String currency;

  public static final String SERIALIZED_NAME_AMOUNT_DETAILS = "amountDetails";
  @SerializedName(SERIALIZED_NAME_AMOUNT_DETAILS)
  private Amount amountDetails;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_FIRST_PAYMENT_AMOUNT = "firstPaymentAmount";
  @SerializedName(SERIALIZED_NAME_FIRST_PAYMENT_AMOUNT)
  private Amount firstPaymentAmount;

  public static final String SERIALIZED_NAME_FIRST_PAYMENT_DATE_TIME = "firstPaymentDateTime";
  @SerializedName(SERIALIZED_NAME_FIRST_PAYMENT_DATE_TIME)
  private OffsetDateTime firstPaymentDateTime;

  public static final String SERIALIZED_NAME_NEXT_PAYMENT_AMOUNT = "nextPaymentAmount";
  @SerializedName(SERIALIZED_NAME_NEXT_PAYMENT_AMOUNT)
  private Amount nextPaymentAmount;

  public static final String SERIALIZED_NAME_NEXT_PAYMENT_DATE_TIME = "nextPaymentDateTime";
  @SerializedName(SERIALIZED_NAME_NEXT_PAYMENT_DATE_TIME)
  private OffsetDateTime nextPaymentDateTime;

  public static final String SERIALIZED_NAME_FINAL_PAYMENT_AMOUNT = "finalPaymentAmount";
  @SerializedName(SERIALIZED_NAME_FINAL_PAYMENT_AMOUNT)
  private Amount finalPaymentAmount;

  public static final String SERIALIZED_NAME_FINAL_PAYMENT_DATE_TIME = "finalPaymentDateTime";
  @SerializedName(SERIALIZED_NAME_FINAL_PAYMENT_DATE_TIME)
  private OffsetDateTime finalPaymentDateTime;

  public static final String SERIALIZED_NAME_NUMBER_OF_PAYMENTS = "numberOfPayments";
  @SerializedName(SERIALIZED_NAME_NUMBER_OF_PAYMENTS)
  private Integer numberOfPayments;

  public static final String SERIALIZED_NAME_PREVIOUS_PAYMENT_AMOUNT = "previousPaymentAmount";
  @SerializedName(SERIALIZED_NAME_PREVIOUS_PAYMENT_AMOUNT)
  private Amount previousPaymentAmount;

  public static final String SERIALIZED_NAME_PREVIOUS_PAYMENT_DATE_TIME = "previousPaymentDateTime";
  @SerializedName(SERIALIZED_NAME_PREVIOUS_PAYMENT_DATE_TIME)
  private OffsetDateTime previousPaymentDateTime;

  public static final String SERIALIZED_NAME_CHARGE_DETAILS = "chargeDetails";
  @SerializedName(SERIALIZED_NAME_CHARGE_DETAILS)
  private List<PaymentChargeDetails> chargeDetails = null;

  public static final String SERIALIZED_NAME_SCHEDULED_PAYMENT_TYPE = "scheduledPaymentType";
  @SerializedName(SERIALIZED_NAME_SCHEDULED_PAYMENT_TYPE)
  private String scheduledPaymentType;

  public static final String SERIALIZED_NAME_SCHEDULED_PAYMENT_DATE_TIME = "scheduledPaymentDateTime";
  @SerializedName(SERIALIZED_NAME_SCHEDULED_PAYMENT_DATE_TIME)
  private OffsetDateTime scheduledPaymentDateTime;

  public static final String SERIALIZED_NAME_FREQUENCY = "frequency";
  @SerializedName(SERIALIZED_NAME_FREQUENCY)
  private FrequencyResponse frequency;

  public static final String SERIALIZED_NAME_CURRENCY_OF_TRANSFER = "currencyOfTransfer";
  @SerializedName(SERIALIZED_NAME_CURRENCY_OF_TRANSFER)
  private String currencyOfTransfer;

  public static final String SERIALIZED_NAME_PURPOSE = "purpose";
  @SerializedName(SERIALIZED_NAME_PURPOSE)
  private String purpose;

  public static final String SERIALIZED_NAME_PRIORITY = "priority";
  @SerializedName(SERIALIZED_NAME_PRIORITY)
  private PriorityCodeEnum priority;

  public static final String SERIALIZED_NAME_EXCHANGE_RATE = "exchangeRate";
  @SerializedName(SERIALIZED_NAME_EXCHANGE_RATE)
  private ExchangeRateInformationResponse exchangeRate;

  public static final String SERIALIZED_NAME_REFUND_ACCOUNT = "refundAccount";
  @SerializedName(SERIALIZED_NAME_REFUND_ACCOUNT)
  private RefundAccount refundAccount;

  public static final String SERIALIZED_NAME_BULK_AMOUNT_SUM = "bulkAmountSum";
  @SerializedName(SERIALIZED_NAME_BULK_AMOUNT_SUM)
  private BigDecimal bulkAmountSum;

  public PaymentResponse() { 
  }

  public PaymentResponse id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public PaymentResponse institutionConsentId(String institutionConsentId) {
    
    this.institutionConsentId = institutionConsentId;
    return this;
  }

   /**
   * Get institutionConsentId
   * @return institutionConsentId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getInstitutionConsentId() {
    return institutionConsentId;
  }


  public void setInstitutionConsentId(String institutionConsentId) {
    this.institutionConsentId = institutionConsentId;
  }


  public PaymentResponse paymentIdempotencyId(String paymentIdempotencyId) {
    
    this.paymentIdempotencyId = paymentIdempotencyId;
    return this;
  }

   /**
   * Get paymentIdempotencyId
   * @return paymentIdempotencyId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPaymentIdempotencyId() {
    return paymentIdempotencyId;
  }


  public void setPaymentIdempotencyId(String paymentIdempotencyId) {
    this.paymentIdempotencyId = paymentIdempotencyId;
  }


  public PaymentResponse paymentLifecycleId(String paymentLifecycleId) {
    
    this.paymentLifecycleId = paymentLifecycleId;
    return this;
  }

   /**
   * Get paymentLifecycleId
   * @return paymentLifecycleId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPaymentLifecycleId() {
    return paymentLifecycleId;
  }


  public void setPaymentLifecycleId(String paymentLifecycleId) {
    this.paymentLifecycleId = paymentLifecycleId;
  }


  public PaymentResponse status(PaymentStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PaymentStatus getStatus() {
    return status;
  }


  public void setStatus(PaymentStatus status) {
    this.status = status;
  }


  public PaymentResponse statusDetails(PaymentStatusDetails statusDetails) {
    
    this.statusDetails = statusDetails;
    return this;
  }

   /**
   * Get statusDetails
   * @return statusDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PaymentStatusDetails getStatusDetails() {
    return statusDetails;
  }


  public void setStatusDetails(PaymentStatusDetails statusDetails) {
    this.statusDetails = statusDetails;
  }


  public PaymentResponse payer(Payer payer) {
    
    this.payer = payer;
    return this;
  }

   /**
   * Get payer
   * @return payer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Payer getPayer() {
    return payer;
  }


  public void setPayer(Payer payer) {
    this.payer = payer;
  }


  public PaymentResponse payeeDetails(Payee payeeDetails) {
    
    this.payeeDetails = payeeDetails;
    return this;
  }

   /**
   * Get payeeDetails
   * @return payeeDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Payee getPayeeDetails() {
    return payeeDetails;
  }


  public void setPayeeDetails(Payee payeeDetails) {
    this.payeeDetails = payeeDetails;
  }


  public PaymentResponse reference(String reference) {
    
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getReference() {
    return reference;
  }


  public void setReference(String reference) {
    this.reference = reference;
  }


  public PaymentResponse amount(BigDecimal amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getAmount() {
    return amount;
  }


  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }


  public PaymentResponse currency(String currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCurrency() {
    return currency;
  }


  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public PaymentResponse amountDetails(Amount amountDetails) {
    
    this.amountDetails = amountDetails;
    return this;
  }

   /**
   * Get amountDetails
   * @return amountDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Amount getAmountDetails() {
    return amountDetails;
  }


  public void setAmountDetails(Amount amountDetails) {
    this.amountDetails = amountDetails;
  }


  public PaymentResponse createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public PaymentResponse firstPaymentAmount(Amount firstPaymentAmount) {
    
    this.firstPaymentAmount = firstPaymentAmount;
    return this;
  }

   /**
   * Get firstPaymentAmount
   * @return firstPaymentAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Amount getFirstPaymentAmount() {
    return firstPaymentAmount;
  }


  public void setFirstPaymentAmount(Amount firstPaymentAmount) {
    this.firstPaymentAmount = firstPaymentAmount;
  }


  public PaymentResponse firstPaymentDateTime(OffsetDateTime firstPaymentDateTime) {
    
    this.firstPaymentDateTime = firstPaymentDateTime;
    return this;
  }

   /**
   * Get firstPaymentDateTime
   * @return firstPaymentDateTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getFirstPaymentDateTime() {
    return firstPaymentDateTime;
  }


  public void setFirstPaymentDateTime(OffsetDateTime firstPaymentDateTime) {
    this.firstPaymentDateTime = firstPaymentDateTime;
  }


  public PaymentResponse nextPaymentAmount(Amount nextPaymentAmount) {
    
    this.nextPaymentAmount = nextPaymentAmount;
    return this;
  }

   /**
   * Get nextPaymentAmount
   * @return nextPaymentAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Amount getNextPaymentAmount() {
    return nextPaymentAmount;
  }


  public void setNextPaymentAmount(Amount nextPaymentAmount) {
    this.nextPaymentAmount = nextPaymentAmount;
  }


  public PaymentResponse nextPaymentDateTime(OffsetDateTime nextPaymentDateTime) {
    
    this.nextPaymentDateTime = nextPaymentDateTime;
    return this;
  }

   /**
   * Get nextPaymentDateTime
   * @return nextPaymentDateTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getNextPaymentDateTime() {
    return nextPaymentDateTime;
  }


  public void setNextPaymentDateTime(OffsetDateTime nextPaymentDateTime) {
    this.nextPaymentDateTime = nextPaymentDateTime;
  }


  public PaymentResponse finalPaymentAmount(Amount finalPaymentAmount) {
    
    this.finalPaymentAmount = finalPaymentAmount;
    return this;
  }

   /**
   * Get finalPaymentAmount
   * @return finalPaymentAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Amount getFinalPaymentAmount() {
    return finalPaymentAmount;
  }


  public void setFinalPaymentAmount(Amount finalPaymentAmount) {
    this.finalPaymentAmount = finalPaymentAmount;
  }


  public PaymentResponse finalPaymentDateTime(OffsetDateTime finalPaymentDateTime) {
    
    this.finalPaymentDateTime = finalPaymentDateTime;
    return this;
  }

   /**
   * Get finalPaymentDateTime
   * @return finalPaymentDateTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getFinalPaymentDateTime() {
    return finalPaymentDateTime;
  }


  public void setFinalPaymentDateTime(OffsetDateTime finalPaymentDateTime) {
    this.finalPaymentDateTime = finalPaymentDateTime;
  }


  public PaymentResponse numberOfPayments(Integer numberOfPayments) {
    
    this.numberOfPayments = numberOfPayments;
    return this;
  }

   /**
   * Get numberOfPayments
   * @return numberOfPayments
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getNumberOfPayments() {
    return numberOfPayments;
  }


  public void setNumberOfPayments(Integer numberOfPayments) {
    this.numberOfPayments = numberOfPayments;
  }


  public PaymentResponse previousPaymentAmount(Amount previousPaymentAmount) {
    
    this.previousPaymentAmount = previousPaymentAmount;
    return this;
  }

   /**
   * Get previousPaymentAmount
   * @return previousPaymentAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Amount getPreviousPaymentAmount() {
    return previousPaymentAmount;
  }


  public void setPreviousPaymentAmount(Amount previousPaymentAmount) {
    this.previousPaymentAmount = previousPaymentAmount;
  }


  public PaymentResponse previousPaymentDateTime(OffsetDateTime previousPaymentDateTime) {
    
    this.previousPaymentDateTime = previousPaymentDateTime;
    return this;
  }

   /**
   * Get previousPaymentDateTime
   * @return previousPaymentDateTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getPreviousPaymentDateTime() {
    return previousPaymentDateTime;
  }


  public void setPreviousPaymentDateTime(OffsetDateTime previousPaymentDateTime) {
    this.previousPaymentDateTime = previousPaymentDateTime;
  }


  public PaymentResponse chargeDetails(List<PaymentChargeDetails> chargeDetails) {
    
    this.chargeDetails = chargeDetails;
    return this;
  }

  public PaymentResponse addChargeDetailsItem(PaymentChargeDetails chargeDetailsItem) {
    if (this.chargeDetails == null) {
      this.chargeDetails = new ArrayList<PaymentChargeDetails>();
    }
    this.chargeDetails.add(chargeDetailsItem);
    return this;
  }

   /**
   * Get chargeDetails
   * @return chargeDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<PaymentChargeDetails> getChargeDetails() {
    return chargeDetails;
  }


  public void setChargeDetails(List<PaymentChargeDetails> chargeDetails) {
    this.chargeDetails = chargeDetails;
  }


  public PaymentResponse scheduledPaymentType(String scheduledPaymentType) {
    
    this.scheduledPaymentType = scheduledPaymentType;
    return this;
  }

   /**
   * Get scheduledPaymentType
   * @return scheduledPaymentType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getScheduledPaymentType() {
    return scheduledPaymentType;
  }


  public void setScheduledPaymentType(String scheduledPaymentType) {
    this.scheduledPaymentType = scheduledPaymentType;
  }


  public PaymentResponse scheduledPaymentDateTime(OffsetDateTime scheduledPaymentDateTime) {
    
    this.scheduledPaymentDateTime = scheduledPaymentDateTime;
    return this;
  }

   /**
   * Get scheduledPaymentDateTime
   * @return scheduledPaymentDateTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getScheduledPaymentDateTime() {
    return scheduledPaymentDateTime;
  }


  public void setScheduledPaymentDateTime(OffsetDateTime scheduledPaymentDateTime) {
    this.scheduledPaymentDateTime = scheduledPaymentDateTime;
  }


  public PaymentResponse frequency(FrequencyResponse frequency) {
    
    this.frequency = frequency;
    return this;
  }

   /**
   * Get frequency
   * @return frequency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public FrequencyResponse getFrequency() {
    return frequency;
  }


  public void setFrequency(FrequencyResponse frequency) {
    this.frequency = frequency;
  }


  public PaymentResponse currencyOfTransfer(String currencyOfTransfer) {
    
    this.currencyOfTransfer = currencyOfTransfer;
    return this;
  }

   /**
   * Get currencyOfTransfer
   * @return currencyOfTransfer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCurrencyOfTransfer() {
    return currencyOfTransfer;
  }


  public void setCurrencyOfTransfer(String currencyOfTransfer) {
    this.currencyOfTransfer = currencyOfTransfer;
  }


  public PaymentResponse purpose(String purpose) {
    
    this.purpose = purpose;
    return this;
  }

   /**
   * Get purpose
   * @return purpose
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPurpose() {
    return purpose;
  }


  public void setPurpose(String purpose) {
    this.purpose = purpose;
  }


  public PaymentResponse priority(PriorityCodeEnum priority) {
    
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PriorityCodeEnum getPriority() {
    return priority;
  }


  public void setPriority(PriorityCodeEnum priority) {
    this.priority = priority;
  }


  public PaymentResponse exchangeRate(ExchangeRateInformationResponse exchangeRate) {
    
    this.exchangeRate = exchangeRate;
    return this;
  }

   /**
   * Get exchangeRate
   * @return exchangeRate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ExchangeRateInformationResponse getExchangeRate() {
    return exchangeRate;
  }


  public void setExchangeRate(ExchangeRateInformationResponse exchangeRate) {
    this.exchangeRate = exchangeRate;
  }


  public PaymentResponse refundAccount(RefundAccount refundAccount) {
    
    this.refundAccount = refundAccount;
    return this;
  }

   /**
   * Get refundAccount
   * @return refundAccount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public RefundAccount getRefundAccount() {
    return refundAccount;
  }


  public void setRefundAccount(RefundAccount refundAccount) {
    this.refundAccount = refundAccount;
  }


  public PaymentResponse bulkAmountSum(BigDecimal bulkAmountSum) {
    
    this.bulkAmountSum = bulkAmountSum;
    return this;
  }

   /**
   * Get bulkAmountSum
   * @return bulkAmountSum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getBulkAmountSum() {
    return bulkAmountSum;
  }


  public void setBulkAmountSum(BigDecimal bulkAmountSum) {
    this.bulkAmountSum = bulkAmountSum;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentResponse paymentResponse = (PaymentResponse) o;
    return Objects.equals(this.id, paymentResponse.id) &&
        Objects.equals(this.institutionConsentId, paymentResponse.institutionConsentId) &&
        Objects.equals(this.paymentIdempotencyId, paymentResponse.paymentIdempotencyId) &&
        Objects.equals(this.paymentLifecycleId, paymentResponse.paymentLifecycleId) &&
        Objects.equals(this.status, paymentResponse.status) &&
        Objects.equals(this.statusDetails, paymentResponse.statusDetails) &&
        Objects.equals(this.payer, paymentResponse.payer) &&
        Objects.equals(this.payeeDetails, paymentResponse.payeeDetails) &&
        Objects.equals(this.reference, paymentResponse.reference) &&
        Objects.equals(this.amount, paymentResponse.amount) &&
        Objects.equals(this.currency, paymentResponse.currency) &&
        Objects.equals(this.amountDetails, paymentResponse.amountDetails) &&
        Objects.equals(this.createdAt, paymentResponse.createdAt) &&
        Objects.equals(this.firstPaymentAmount, paymentResponse.firstPaymentAmount) &&
        Objects.equals(this.firstPaymentDateTime, paymentResponse.firstPaymentDateTime) &&
        Objects.equals(this.nextPaymentAmount, paymentResponse.nextPaymentAmount) &&
        Objects.equals(this.nextPaymentDateTime, paymentResponse.nextPaymentDateTime) &&
        Objects.equals(this.finalPaymentAmount, paymentResponse.finalPaymentAmount) &&
        Objects.equals(this.finalPaymentDateTime, paymentResponse.finalPaymentDateTime) &&
        Objects.equals(this.numberOfPayments, paymentResponse.numberOfPayments) &&
        Objects.equals(this.previousPaymentAmount, paymentResponse.previousPaymentAmount) &&
        Objects.equals(this.previousPaymentDateTime, paymentResponse.previousPaymentDateTime) &&
        Objects.equals(this.chargeDetails, paymentResponse.chargeDetails) &&
        Objects.equals(this.scheduledPaymentType, paymentResponse.scheduledPaymentType) &&
        Objects.equals(this.scheduledPaymentDateTime, paymentResponse.scheduledPaymentDateTime) &&
        Objects.equals(this.frequency, paymentResponse.frequency) &&
        Objects.equals(this.currencyOfTransfer, paymentResponse.currencyOfTransfer) &&
        Objects.equals(this.purpose, paymentResponse.purpose) &&
        Objects.equals(this.priority, paymentResponse.priority) &&
        Objects.equals(this.exchangeRate, paymentResponse.exchangeRate) &&
        Objects.equals(this.refundAccount, paymentResponse.refundAccount) &&
        Objects.equals(this.bulkAmountSum, paymentResponse.bulkAmountSum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, institutionConsentId, paymentIdempotencyId, paymentLifecycleId, status, statusDetails, payer, payeeDetails, reference, amount, currency, amountDetails, createdAt, firstPaymentAmount, firstPaymentDateTime, nextPaymentAmount, nextPaymentDateTime, finalPaymentAmount, finalPaymentDateTime, numberOfPayments, previousPaymentAmount, previousPaymentDateTime, chargeDetails, scheduledPaymentType, scheduledPaymentDateTime, frequency, currencyOfTransfer, purpose, priority, exchangeRate, refundAccount, bulkAmountSum);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    institutionConsentId: ").append(toIndentedString(institutionConsentId)).append("\n");
    sb.append("    paymentIdempotencyId: ").append(toIndentedString(paymentIdempotencyId)).append("\n");
    sb.append("    paymentLifecycleId: ").append(toIndentedString(paymentLifecycleId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusDetails: ").append(toIndentedString(statusDetails)).append("\n");
    sb.append("    payer: ").append(toIndentedString(payer)).append("\n");
    sb.append("    payeeDetails: ").append(toIndentedString(payeeDetails)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    amountDetails: ").append(toIndentedString(amountDetails)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    firstPaymentAmount: ").append(toIndentedString(firstPaymentAmount)).append("\n");
    sb.append("    firstPaymentDateTime: ").append(toIndentedString(firstPaymentDateTime)).append("\n");
    sb.append("    nextPaymentAmount: ").append(toIndentedString(nextPaymentAmount)).append("\n");
    sb.append("    nextPaymentDateTime: ").append(toIndentedString(nextPaymentDateTime)).append("\n");
    sb.append("    finalPaymentAmount: ").append(toIndentedString(finalPaymentAmount)).append("\n");
    sb.append("    finalPaymentDateTime: ").append(toIndentedString(finalPaymentDateTime)).append("\n");
    sb.append("    numberOfPayments: ").append(toIndentedString(numberOfPayments)).append("\n");
    sb.append("    previousPaymentAmount: ").append(toIndentedString(previousPaymentAmount)).append("\n");
    sb.append("    previousPaymentDateTime: ").append(toIndentedString(previousPaymentDateTime)).append("\n");
    sb.append("    chargeDetails: ").append(toIndentedString(chargeDetails)).append("\n");
    sb.append("    scheduledPaymentType: ").append(toIndentedString(scheduledPaymentType)).append("\n");
    sb.append("    scheduledPaymentDateTime: ").append(toIndentedString(scheduledPaymentDateTime)).append("\n");
    sb.append("    frequency: ").append(toIndentedString(frequency)).append("\n");
    sb.append("    currencyOfTransfer: ").append(toIndentedString(currencyOfTransfer)).append("\n");
    sb.append("    purpose: ").append(toIndentedString(purpose)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    exchangeRate: ").append(toIndentedString(exchangeRate)).append("\n");
    sb.append("    refundAccount: ").append(toIndentedString(refundAccount)).append("\n");
    sb.append("    bulkAmountSum: ").append(toIndentedString(bulkAmountSum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

