/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.14.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.starter.domain.yapilymodels;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.LinkedHashSet;
import java.util.Objects;
import java.util.Set;

/**
 * VirtualAccountBankAccount
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-16T14:42:32.575816279Z[Europe/London]")
public class VirtualAccountBankAccount {
  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private String currency;

  public static final String SERIALIZED_NAME_BANK_NAME = "bankName";
  @SerializedName(SERIALIZED_NAME_BANK_NAME)
  private String bankName;

  public static final String SERIALIZED_NAME_BANK_ADDRESS = "bankAddress";
  @SerializedName(SERIALIZED_NAME_BANK_ADDRESS)
  private String bankAddress;

  public static final String SERIALIZED_NAME_BANK_COUNTRY = "bankCountry";
  @SerializedName(SERIALIZED_NAME_BANK_COUNTRY)
  private String bankCountry;

  public static final String SERIALIZED_NAME_ACCOUNT_IDENTIFICATIONS = "accountIdentifications";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_IDENTIFICATIONS)
  private Set<AccountIdentification> accountIdentifications = null;

  public static final String SERIALIZED_NAME_PAY_IN_REFERENCE = "payInReference";
  @SerializedName(SERIALIZED_NAME_PAY_IN_REFERENCE)
  private String payInReference;

  public VirtualAccountBankAccount() { 
  }

  public VirtualAccountBankAccount currency(String currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * Three-letter ISO 4217 currency code
   * @return currency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "GBP", value = "Three-letter ISO 4217 currency code")

  public String getCurrency() {
    return currency;
  }


  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public VirtualAccountBankAccount bankName(String bankName) {
    
    this.bankName = bankName;
    return this;
  }

   /**
   * Get bankName
   * @return bankName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lloyds Bank", value = "")

  public String getBankName() {
    return bankName;
  }


  public void setBankName(String bankName) {
    this.bankName = bankName;
  }


  public VirtualAccountBankAccount bankAddress(String bankAddress) {
    
    this.bankAddress = bankAddress;
    return this;
  }

   /**
   * Get bankAddress
   * @return bankAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "WE12 ABC", value = "")

  public String getBankAddress() {
    return bankAddress;
  }


  public void setBankAddress(String bankAddress) {
    this.bankAddress = bankAddress;
  }


  public VirtualAccountBankAccount bankCountry(String bankCountry) {
    
    this.bankCountry = bankCountry;
    return this;
  }

   /**
   * Two-letter ISO 3166 country code
   * @return bankCountry
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "GB", value = "Two-letter ISO 3166 country code")

  public String getBankCountry() {
    return bankCountry;
  }


  public void setBankCountry(String bankCountry) {
    this.bankCountry = bankCountry;
  }


  public VirtualAccountBankAccount accountIdentifications(Set<AccountIdentification> accountIdentifications) {
    
    this.accountIdentifications = accountIdentifications;
    return this;
  }

  public VirtualAccountBankAccount addAccountIdentificationsItem(AccountIdentification accountIdentificationsItem) {
    if (this.accountIdentifications == null) {
      this.accountIdentifications = new LinkedHashSet<AccountIdentification>();
    }
    this.accountIdentifications.add(accountIdentificationsItem);
    return this;
  }

   /**
   * The account identifications that identify the Beneficiary bank account.
   * @return accountIdentifications
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[{\"identification\":\"401016\",\"type\":\"SORT_CODE\"},{\"identification\":\"71518920\",\"type\":\"ACCOUNT_NUMBER\"}]", value = "The account identifications that identify the Beneficiary bank account.")

  public Set<AccountIdentification> getAccountIdentifications() {
    return accountIdentifications;
  }


  public void setAccountIdentifications(Set<AccountIdentification> accountIdentifications) {
    this.accountIdentifications = accountIdentifications;
  }


  public VirtualAccountBankAccount payInReference(String payInReference) {
    
    this.payInReference = payInReference;
    return this;
  }

   /**
   * Reference required for paying into the account. When no reference is provided, then one is not required to pay into the acount.
   * @return payInReference
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Ref1249944", value = "Reference required for paying into the account. When no reference is provided, then one is not required to pay into the acount.")

  public String getPayInReference() {
    return payInReference;
  }


  public void setPayInReference(String payInReference) {
    this.payInReference = payInReference;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VirtualAccountBankAccount virtualAccountBankAccount = (VirtualAccountBankAccount) o;
    return Objects.equals(this.currency, virtualAccountBankAccount.currency) &&
        Objects.equals(this.bankName, virtualAccountBankAccount.bankName) &&
        Objects.equals(this.bankAddress, virtualAccountBankAccount.bankAddress) &&
        Objects.equals(this.bankCountry, virtualAccountBankAccount.bankCountry) &&
        Objects.equals(this.accountIdentifications, virtualAccountBankAccount.accountIdentifications) &&
        Objects.equals(this.payInReference, virtualAccountBankAccount.payInReference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currency, bankName, bankAddress, bankCountry, accountIdentifications, payInReference);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VirtualAccountBankAccount {\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    bankName: ").append(toIndentedString(bankName)).append("\n");
    sb.append("    bankAddress: ").append(toIndentedString(bankAddress)).append("\n");
    sb.append("    bankCountry: ").append(toIndentedString(bankCountry)).append("\n");
    sb.append("    accountIdentifications: ").append(toIndentedString(accountIdentifications)).append("\n");
    sb.append("    payInReference: ").append(toIndentedString(payInReference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

