/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.14.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.starter.domain.yapilymodels;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

/**
 * VirtualAccountClient
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-16T14:42:32.575816279Z[Europe/London]")
public class VirtualAccountClient {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private VirtualAccountClientType type;

  public static final String SERIALIZED_NAME_KYC_STATUS = "kycStatus";
  @SerializedName(SERIALIZED_NAME_KYC_STATUS)
  private VirtualAccountKycStatus kycStatus;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private VirtualAccountClientStatus status;

  public static final String SERIALIZED_NAME_CREATED_DATE_TIME = "createdDateTime";
  @SerializedName(SERIALIZED_NAME_CREATED_DATE_TIME)
  private OffsetDateTime createdDateTime;

  public static final String SERIALIZED_NAME_INDIVIDUAL = "individual";
  @SerializedName(SERIALIZED_NAME_INDIVIDUAL)
  private VirtualAccountIndividualClient individual;

  public static final String SERIALIZED_NAME_BUSINESS = "business";
  @SerializedName(SERIALIZED_NAME_BUSINESS)
  private VirtualAccountBusinessClient business;

  public VirtualAccountClient() { 
  }

  public VirtualAccountClient id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The id generated in the on-boarding process, it will be used as client-id for virtual accounts request
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "cf996ecc-8720-4bb3-8dbb-fe9018e0db12", value = "The id generated in the on-boarding process, it will be used as client-id for virtual accounts request")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public VirtualAccountClient type(VirtualAccountClientType type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VirtualAccountClientType getType() {
    return type;
  }


  public void setType(VirtualAccountClientType type) {
    this.type = type;
  }


  public VirtualAccountClient kycStatus(VirtualAccountKycStatus kycStatus) {
    
    this.kycStatus = kycStatus;
    return this;
  }

   /**
   * Get kycStatus
   * @return kycStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VirtualAccountKycStatus getKycStatus() {
    return kycStatus;
  }


  public void setKycStatus(VirtualAccountKycStatus kycStatus) {
    this.kycStatus = kycStatus;
  }


  public VirtualAccountClient status(VirtualAccountClientStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VirtualAccountClientStatus getStatus() {
    return status;
  }


  public void setStatus(VirtualAccountClientStatus status) {
    this.status = status;
  }


  public VirtualAccountClient createdDateTime(OffsetDateTime createdDateTime) {
    
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }


  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }


  public VirtualAccountClient individual(VirtualAccountIndividualClient individual) {
    
    this.individual = individual;
    return this;
  }

   /**
   * Get individual
   * @return individual
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VirtualAccountIndividualClient getIndividual() {
    return individual;
  }


  public void setIndividual(VirtualAccountIndividualClient individual) {
    this.individual = individual;
  }


  public VirtualAccountClient business(VirtualAccountBusinessClient business) {
    
    this.business = business;
    return this;
  }

   /**
   * Get business
   * @return business
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VirtualAccountBusinessClient getBusiness() {
    return business;
  }


  public void setBusiness(VirtualAccountBusinessClient business) {
    this.business = business;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VirtualAccountClient virtualAccountClient = (VirtualAccountClient) o;
    return Objects.equals(this.id, virtualAccountClient.id) &&
        Objects.equals(this.type, virtualAccountClient.type) &&
        Objects.equals(this.kycStatus, virtualAccountClient.kycStatus) &&
        Objects.equals(this.status, virtualAccountClient.status) &&
        Objects.equals(this.createdDateTime, virtualAccountClient.createdDateTime) &&
        Objects.equals(this.individual, virtualAccountClient.individual) &&
        Objects.equals(this.business, virtualAccountClient.business);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, kycStatus, status, createdDateTime, individual, business);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VirtualAccountClient {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    kycStatus: ").append(toIndentedString(kycStatus)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    individual: ").append(toIndentedString(individual)).append("\n");
    sb.append("    business: ").append(toIndentedString(business)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

